### ISSUE TITLE
Categorical Filtering Error

### ISSUE THREAD

**Issue by angelachawla** [jupytercalpoly/Jupyter-Bifrost#100]
**Describe the bug**
In some categorical filters, checkboxes are unclickable. This is specifically the case with the "alone" and "survived" datafields in the Titanic dataset. For "alone", labels also do not appear next to checkboxes.

**To Reproduce**
1. Add "alone" or "survived" as a new variable.
2. Click on filter.
3. Attempt to check / uncheck boxes.

**Expected behavior**
Boxes should be selected / deselected on click. Labels should appear next to boxes.

**Screen Recording**
https://user-images.githubusercontent.com/83424843/129110359-c106d447-be5c-4de2-8458-1ef3a5568791.mov

**Comment by Waidhoferj** [comment]
Fixed in #108
