### ISSUE TITLE
Circle Chart Crash

### ISSUE THREAD

**Issue by angelachawla** [jupytercalpoly/Jupyter-Bifrost#102]
**Describe the bug**
Adding a new variable to a circle chart sometimes crashes the extension.

**To Reproduce**
1. Create a histogram.
2. Change chart type to circle.
3. Delete y-variable.
4. Assign a datafield to the x-pill.
5. Add a new variable. This will crash the extension.

**Expected behavior**
User should be able to assign a datafield to the x-pill and add a new data pill.

**Screen Recording**
https://user-images.githubusercontent.com/83424843/129117934-423ae068-302a-421a-9ed1-fa6f36366142.mov

**Comment by Waidhoferj** [comment]
Tested with scatter, since we no longer support circle. Issue appears to be fixed
