### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#106]
**Describe the bug**
Change the variable type and add filter crashes the app

**To Reproduce**
1. Plot bifrost with age and class
2. Go to datatab and convert age type to categorical
3. Click filter

**Expected behavior**
App shouldn't crash

**Screenshots**
![Kapture 2021-08-13 at 10 42 04](https://user-images.githubusercontent.com/15991814/129403063-258e016f-0311-466e-ae10-7c14b888d2c6.gif)

**Comment by Waidhoferj** [comment]
Tested. This has been fixed.
