### ISSUE TITLE
The number of data on graph

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#133]
It looks like the number of data on graph doesn't match with sampling. Sampling says it shows the 100% of dataset, but a few data points on graph seem filtered.
<img width="1035" alt="Screen Shot 2021-08-19 at 10 52 10 AM" src="https://user-images.githubusercontent.com/15991814/130119606-5b15f503-2b0c-46d5-9f31-467fee9230a2.png">

**Comment by Waidhoferj** [comment]
Resampling likely causes the max and min values to change. I'll check this out.
