### ISSUE TITLE
The bounds calculcation is failing for sliders

### ISSUE THREAD

**Issue by Waidhoferj** [jupytercalpoly/Jupyter-Bifrost#155]
<img width="807" alt="Screen Shot 2021-08-27 at 12 28 58 PM" src="https://user-images.githubusercontent.com/33008436/131179249-b3fcde4f-f031-4d30-bbc2-d6226805c003.png">

**Seen**
Max value of AirTankers is 21...

**Expected**
Max value should be 5 (see graph)

**Comment by jahn96** [comment]
Think this is working correctly. The maximum value is 27
