### ISSUE TITLE
Question about updating of the graph on the visualization screen

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#41]
## Question
Should we see the pie chart on the main visualization screen when theta and color are selected as two variables in data tab?

## Discussion
After creating a scatter plot with x and y variables, I deleted x and y pills and created a theta pill and a color pill. On the main visualization screen, I don't see any graph. I think it's because the mark is set as a point. It might be good to not show the channels that are not applicable.

## Current State
![Kapture 2021-07-15 at 16 34 48](https://user-images.githubusercontent.com/15991814/125871509-0b709834-0402-40fe-910a-489732824175.gif)

**Comment by Waidhoferj** [comment]
Pie charts no longer included
