### ISSUE TITLE
Branching History

### ISSUE THREAD

**Issue by angelachawla** [jupytercalpoly/Jupyter-Bifrost#45]
Implement a branching history design system to allow users to return to previous states of their visualization, and explore several different approaches of edits to those states.

This would be an update on the current, strictly linear and time-based history system. 

Questions about merging secondary branches into the main branch and how many layers of branches a user can add will continue to be worked through. In addition, features like a searchable history, bookmarking, and duplicating or deleting history states may be useful.

Here are some initial low-fi screen designs.
<img width="1199" alt="Screen Shot 2021-07-19 at 11 04 29 AM" src="https://user-images.githubusercontent.com/83424843/126206226-82788370-580d-447b-bc80-7b7006fbdc86.png">
<img width="1200" alt="Screen Shot 2021-07-19 at 11 04 45 AM" src="https://user-images.githubusercontent.com/83424843/126206229-a8fbf109-2fc1-4bf5-afa8-8874a8003fed.png">

**Comment by Waidhoferj** [comment]
Decided to go with linear history
