### ISSUE TITLE
Adding icons for variable's data type in a pill

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#55]
**Is your feature request related to a problem? Please describe.**
Currently, in a pill, it's hard to know whether the variable is qualitative or quantitative in a pill. In some ways, a column with the numeric values can be used as a categorical column.

**Describe the solution you'd like**
Have an icon that indicates the data type next to the name of the variable.

**Describe alternatives you've considered**
* Show data type on hover
* Show data type as a text next to the title.

**Comment by angelachawla** [comment]
We could do something more literal like this:
<img width="207" alt="Screen Shot 2021-07-22 at 11 17 40 AM" src="https://user-images.githubusercontent.com/83424843/126689010-67256d42-c9b6-49be-b59f-3eb4ea9ed251.png">

Or something more abstract like this:
<img width="229" alt="Screen Shot 2021-07-22 at 11 17 36 AM" src="https://user-images.githubusercontent.com/83424843/126689045-7075d8c1-068c-479e-99d4-e21afb29b3c4.png">
