### ISSUE TITLE
Persistent Branching History Tree

### ISSUE THREAD

**Issue by angelachawla** [jupytercalpoly/Jupyter-Bifrost#58]
Implement a branching history tree that is available throughout the user-interface will allow users to use the history as an iterative navigation tool. 

This would be an update on the current system, which is limited to the history tab in the slide-out menu. 

This design has a collapsed and expanded view, preventing it from being too distracting to users. Larger nodes could indicate larger or more important changes, such as mark changes. Multiple similar interactions could be chunked together in each node, preventing an unreasonably large number of nodes. To save space, colored markers can be used to indicate if a node has a branch. 

Some questions to consider in the future will be what collapsed views look like if the user is several branches deep in the iterative history. Another is if hover states should be implemented that include thumbnails or tooltip info. We could also consider using icons or a color coding system to easily visually categorize different kinds of interactions. 

Limits will also have to be placed on the tree. A single node should not have more than three siblings, and only 3 levels of branching will be supported.

Here are some initial low-fi iterations.
<img width="917" alt="Screen Shot 2021-07-22 at 9 49 32 AM" src="https://user-images.githubusercontent.com/83424843/126677696-c5a2c223-5da0-4970-85e5-09161c534869.png">
<img width="914" alt="Screen Shot 2021-07-22 at 9 49 46 AM" src="https://user-images.githubusercontent.com/83424843/126677704-42224bed-3840-4101-a639-af3eb6f56210.png">
<img width="936" alt="Screen Shot 2021-07-22 at 9 49 54 AM" src="https://user-images.githubusercontent.com/83424843/126677712-2a8f902a-82ac-455e-96b3-e018e073c5e3.png">
<img width="908" alt="Screen Shot 2021-07-22 at 9 50 13 AM" src="https://user-images.githubusercontent.com/83424843/126677718-c5735c21-2e11-4a60-b7d3-a9574f47307a.png">

**Comment by Waidhoferj** [comment]
Decided to go with linear history
