### ISSUE TITLE
File System History

### ISSUE THREAD

**Issue by angelachawla** [jupytercalpoly/Jupyter-Bifrost#65]
Reformat the history section to use a metaphor similar to a file system. 

Our current model of a branching tree, from a user perspective, is difficult to comprehend and cumbersome to navigate. Simplifying it to a file system format pulls on a metaphor likely familiar to the user, making it much more intuitive. 

We have also looked at making a tree easier to navigate by simplifying it into a limited number of branching nodes. We have also looked at using a "snapshot" system similar to Photoshop's mechanics, where the user can elect to save a duplicate of a current state. Histories of edits are preserved for both states, creating a simplified branching history. 

<img width="330" alt="Screen Shot 2021-07-28 at 5 29 18 PM" src="https://user-images.githubusercontent.com/83424843/127413601-263c9e06-c15b-413d-af15-52f32a9d5420.png">
<img width="333" alt="Screen Shot 2021-07-28 at 5 29 24 PM" src="https://user-images.githubusercontent.com/83424843/127413602-0cb32844-bbfd-42bc-aa8e-f1ed44dc6fdf.png">
<img width="336" alt="Screen Shot 2021-07-28 at 5 29 30 PM" src="https://user-images.githubusercontent.com/83424843/127413604-e2e3fe1c-2720-430a-9b65-5c2cb10d423d.png">
<img width="343" alt="Screen Shot 2021-07-28 at 5 29 57 PM" src="https://user-images.githubusercontent.com/83424843/127413605-d28dc23a-b4ca-4e1f-acae-74164822a6c1.png">

**Comment by Waidhoferj** [comment]
Decided to go with linear history
