### ISSUE TITLE
Show range and categories in the pill

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#80]
I think it would be better to show the full range and all categories initially in the pills.
**Current State**:
![Screen Shot 2021-08-05 at 10 25 30 AM](https://user-images.githubusercontent.com/15991814/128394564-29c0b6a1-37b1-4ab6-a512-34f52cad6cb6.png)
**Expected State**:
![Screen Shot 2021-08-05 at 10 25 53 AM](https://user-images.githubusercontent.com/15991814/128394567-c2c67c84-ff98-4757-a2ea-f84b927e0120.png)

**Comment by angelachawla** [comment]
I could definitely see that being helpful. I think a problem I see with that is if there are more categorical rows than the pill can handle. Maybe we could cap it at certain amount with an ellipses at the end of the list?
