### ISSUE TITLE
Graph Pill Bugs

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/Jupyter-Bifrost#81]
This is the list of bugs related to graph pills. Feel free to add it here if you find one.
* The app gets crashed when the filter icon in the pill without the column name is clicked.
![Kapture 2021-08-05 at 10 27 11](https://user-images.githubusercontent.com/15991814/128394749-ea7d74fd-12fe-488c-8318-e210700649e3.gif)

**Comment by Waidhoferj** [comment]
Fixed in #108
